'use strict';

var jwt = require('jwt-simple');
var path = require('path');

var config = require(path.resolve('./lib/config'));

exports.decode = decode;

//////////

/**
 * Decode a token
 *
 * @param {ExpressRequestObject} req The request object generated by express.
 * @param {ExpressResponseObject} res The response object generated by express.
 * @param {function} next
 */

function decode (req, res, next) {
  var token = req.headers['x-access-token'];
  var user;
  if (!token) {
    // Set the user to null if a token is not provided
    req.user = null;
    next();
  } else {
    try {
      // decode token and attach user to the request
      // for use inside our controllers
      user = jwt.decode(token, config.secret);
      req.user = user;
      next();
    } catch(error) {
      // if token decode fails, set user to null and continue
      req.user = null;
      next();
    }


  }

}
