'use strict';

// var _ = require('lodash');
var path = require('path');

var db = require(path.resolve('./lib/db.js'));

exports.createPage = createPage;
exports.deletePage = deletePage;
exports.getPageByIdOrSlug = getPageByIdOrSlug;
exports.getPages = getPages;
exports.sendPage = sendPage;
exports.updatePage = updatePage;

//////////

/**
 * Creates a page in the database
 *
 * @param {ExpressRequestObject} req The request object generated by express.
 * @param {ExpressResponseObject} res The response object generated by express.
 */

function createPage (req, res) {
  var page = {};
  page.content = req.body.content;
  page.slug = checkSlug(req.body.slug);
  page.title = req.body.title;

  db.Page.create(page)
    .then(sendCreatedPage)
    .catch(send500);

  //////////

  function checkSlug (slug) {
    if (slug[0] === '/') {
      return slug;
    } else {
      return '/' + slug;
    }
  }

  function send500 () {
    res.status(500).send('Database Error: Page could not be Created');
  }

  function sendCreatedPage (page) {
    res.status(200).send(page);
  }

}

/**
 * Deletes a page from the database
 *
 * @param {ExpressRequestObject} req The request object generated by express.
 * @param {ExpressResponseObject} res The response object generated by express.
 */

function deletePage (req, res) {
  db.Page.destroy({ where: { id: req.page.id } })
    .then(sendDeletedPage)
    .catch(send500);

  function send500 () {
    res.status(500).send('Database Error: Page could not be deleted.');
  }

  function sendDeletedPage (page) {
    res.sendStatus(200);
  }

}

/**
 * Gets a page by a given id or slug. Prioritizes ID, checks for slug if not a number
 *
 * @param {ExpressRequestObject} req The request object generated by express.
 * @param {ExpressResponseObject} res The response object generated by express.
 * @param {function} next
 * @param {string} id The page id given in the route
 */

function getPageByIdOrSlug (req, res, next, id) {
  // Tests if id can be stringified into a number. If so it's an ID and query as such
  var pageQuery;
  if (+id){
    pageQuery = {
      where: {
        id: id
      }
    };
  // If not, it's a string and should be queried based on slug
  } else {
    pageQuery = {
      where: {
        slug: '/' + id
      }
    };
  }

  db.Page.findOne(pageQuery)
    .then(goToNext)
    .catch(send500);

  //////////

  function goToNext (page) {
    req.page = page;
    next();
  }

  function send500 () {
    res.status(500).send('Database Error: Could not retrieve Page');
  }
}

/**
 * Get all pages from the database.
 *
 * @param {ExpressRequestObject} req The request object generated by express.
 * @param {ExpressResponseObject} res The response object generated by express.
 */

function getPages (req, res) {
  db.Page.findAll()
    .then(sendPageInfo)
    .catch(send500);

  //////////

  function send500 () {
    res.status(500).send('Database Error: Could not retrieve Pages.');
  }

  function sendPageInfo (pages) {
    var output = [];
    var plainPage;
    pages.forEach(function (page) {
      plainPage = page.get({plain:true});
      delete plainPage.content;
      output.push(plainPage);
    });
    res.status(200).send(output);
  }

}

/**
 * Sends back a page, if the page exists on the req object.
 * The page is set on the req object, in other functions.
 *
 * @param {ExpressRequestObject} req The request object generated by express.
 * @param {ExpressResponseObject} res The response object generated by express.
 */

function sendPage (req, res) {
  if(req.page) {
    var tabQuery = {
      where: {
        uisref: 'pages.'+req.page.id
      }
    };

    db.Tab.findOne(tabQuery)
      .then(composePage)
      .then(send200)
      .catch(send500);
  } else {
    res.status(400).send('Page does not exist');
  }

  //////////

  function composePage(tab) {
    var page = {};
    page.id = req.page.id;
    page.content = req.page.content;
    page.slug = req.page.slug;
    page.title = req.page.title;
    page.createdAt = req.page.createdAt;
    page.updatedAt = req.page.updatedAt;

    if (tab) {
      page.tab = tab;
    }

    return page;
  }

  function send200(page) {
    res.status(200).send(page);
  }

  function send500() {
    res.status(500).send('Database Error Occured');
  }
}

/**
 * Updates a page in the database
 *
 * @param {ExpressRequestObject} req The request object generated by express.
 * @param {ExpressResponseObject} res The response object generated by express.
 */

function updatePage (req, res) {
  var page = {};
  page.content = req.body.content || req.page.content;
  page.slug = req.body.slug || req.page.slug;
  page.title = req.body.title || req.page.title;

  var pageQuery = {
    where: {
      id: req.page.id
    }
  };

  db.Page.update(page, pageQuery)
    .then(findUpdatedPage)
    .then(sendUpdatedPage)
    .catch(send500);

  //////////

  function findUpdatedPage () {
    var pageQuery = {
      where: {
        id: req.page.id
      }
    };

    return db.Page.findOne(pageQuery);
  }

  function send500 () {
    res.status(500).send('Database Error: Page could not be updated');
  }

  function sendUpdatedPage (page) {
    res.status(200).send(page);
  }

}
